// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1) {
  return window['go']['main']['App']['ChangeDirectory'](arg1);
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function InitExistingProject(arg1, arg2) {
  return window['go']['main']['App']['InitExistingProject'](arg1, arg2);
}

export function InitNewProject(arg1, arg2) {
  return window['go']['main']['App']['InitNewProject'](arg1, arg2);
}

export function ProjectExists(arg1) {
  return window['go']['main']['App']['ProjectExists'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StateFileExists(arg1) {
  return window['go']['main']['App']['StateFileExists'](arg1);
}
