// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
