// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1:string):Promise<void>;

export function WorkOn(arg1:string):Promise<string>;

export function GetInfo():Promise<Array<string>>;

export function InitExistingProject(arg1:string,arg2:string):Promise<void>;

export function InitNewProject(arg1:string,arg2:string):Promise<void>;

export function ProjectExists(arg1:string):Promise<boolean>;

export function SelectDirectory():Promise<string>;

export function StateFileExists(arg1:string):Promise<boolean>;
